apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: active-active-argo
  namespace: argo
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - cluster: node01
            url: https://kubernetes.default.svc
            wave: "1"
          - cluster: node02
            url: https://172.16.0.111:6443
            wave: "2"
  template:
    metadata:
      name: 'app-{{.cluster}}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{.wave}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/bernardolsp/active-active-argo.git
        targetRevision: HEAD
        path: app-default
        helm:
          values: |
            cluster_name: '{{.cluster}}'
            ingress:
              enabled: true
              host: 'app-{{.cluster}}.bernardolopes.com'
      destination:
        namespace: active-active-argo
        server: '{{ .url }}'
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
        - CreateNamespace=true