apiVersion: batch/v1
kind: Job
metadata:
  generateName: {{ .Release.Name }}-postdeploy-job-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: cloudflare-lb-thingy
        image: devlopesbernardo/cloudflare-lb-thingy:x86
        imagePullPolicy: Always
        env:
          - name: EMAIL
            valueFrom:
              secretKeyRef:
                name: cloudflare-secret
                key: EMAIL
                optional: false
          - name: API_KEY
            valueFrom:
              secretKeyRef:
                name: cloudflare-secret
                key: API_KEY
                optional: false
          - name: POOL_ID
            valueFrom:
              secretKeyRef:
                name: cloudflare-secret
                key: POOL_ID
                optional: false
          - name: ACCOUNT_ID
            valueFrom:
              secretKeyRef:
                name: cloudflare-secret
                key: ACCOUNT_ID
                optional: false
          - name: URLS
            value: "google.com,facebook.com"
      restartPolicy: OnFailure